version: '3.8'
services:
  db:
    image: postgres
    ports:
      - "5433:5432" # Changed from 5432:5433 to 5433:5432
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080" # Changed from 8080:8080 to 8081:8080
